apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    index: "logstash-*"
    isDefault: false
    editable: true
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"